Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,16 +18,30 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: '22.5.1'
-        
+
+      - name: Create SSH Key
+        env:
+          KEY: ${{ secrets.SERVER_SSH_KEY }}
+        run: |
+          mkdir -p ~/.ssh
+          echo "$KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa  # Set permissions to read/write for the owner only
+          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts  # Avoid SSH prompts
+
       - name: Copy .env from Server
         env:
           HOST: ${{ secrets.SERVER_HOST }}
           USERNAME: ${{ secrets.SERVER_USERNAME }}
           PORT: ${{ secrets.SERVER_PORT }}
-          KEY: ${{ secrets.SERVER_SSH_KEY }}
-          ENV_PATH: ${{secrets.SERVER_ENV_PATH}}
         run: |
-          scp -i $KEY -P $PORT $USERNAME@$HOST:$ENV_PATH .env
+          # Use the newly created SSH key to copy the .env file from the server
+          scp -P $PORT $USERNAME@$HOST:~/labguy-server/.env .env
+
+      - name: Verify .env file
+        run: |
+          # Check if the .env file has been copied correctly
+          ls -la .env
+          cat .env
 
       - name: Load environment variables
         run: |
@@ -47,12 +61,12 @@ jobs:
           HOST: ${{ secrets.SERVER_HOST }}
           USERNAME: ${{ secrets.SERVER_USERNAME }}
           PORT: ${{ secrets.SERVER_PORT }}
-          KEY: ${{ secrets.SERVER_SSH_KEY }}
         run: |
-          ssh -i $KEY -o StrictHostKeyChecking=no -p $PORT $USERNAME@$HOST << 'EOF'
-            cd /path/to/your/app
+          # Deploy to the server using the created SSH key
+          ssh -p $PORT $USERNAME@$HOST << 'EOF'
+            cd ~/labguy-server || { echo "Directory not found"; exit 1; }
             git pull origin main
             npm install
             npm run build
-            pm2 restart <app_name>
+            pm2 restart www
           EOF
